// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8vxDSOKIw418InCdiTcLNXOcYNQyTXBE',
    appId: '1:312467378240:web:8d7de499c6a4b3b9ae0fa5',
    messagingSenderId: '312467378240',
    projectId: 'smart-posture-63f20',
    authDomain: 'smart-posture-63f20.firebaseapp.com',
    databaseURL: 'https://smart-posture-63f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-posture-63f20.appspot.com',
    measurementId: 'G-L1WLXBDW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeb5BeDTMkP0ObCgM3vQY-YY7_JQyAjgo',
    appId: '1:312467378240:android:06624f0ef3e84396ae0fa5',
    messagingSenderId: '312467378240',
    projectId: 'smart-posture-63f20',
    databaseURL: 'https://smart-posture-63f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-posture-63f20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy62pOwDo7xwPX5k4XW2T2KaDSwq-T4xs',
    appId: '1:312467378240:ios:b21061d226dd67f1ae0fa5',
    messagingSenderId: '312467378240',
    projectId: 'smart-posture-63f20',
    storageBucket: 'smart-posture-63f20.appspot.com',
    databaseURL: 'https://smart-posture-63f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosClientId: '312467378240-ngqg4a29d15eej1626avoodv52ptaoua.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy62pOwDo7xwPX5k4XW2T2KaDSwq-T4xs',
    appId: '1:312467378240:ios:b21061d226dd67f1ae0fa5',
    messagingSenderId: '312467378240',
    projectId: 'smart-posture-63f20',
    storageBucket: 'smart-posture-63f20.appspot.com',
    databaseURL: 'https://smart-posture-63f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosClientId: '312467378240-ngqg4a29d15eej1626avoodv52ptaoua.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
